print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/rvinluan/Documents/Building Worlds/Building-Worlds/FishLab/Assets/fishmodel.ma"`)
{		
	file -o "/Users/rvinluan/Documents/Building Worlds/Building-Worlds/FishLab/Assets/fishmodel.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/rvinluan/Documents/Building Worlds/Building-Worlds/FishLab/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/rvinluan/Documents/Building Worlds/Building-Worlds/FishLab/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/rvinluan/Documents/Building Worlds/Building-Worlds/FishLab/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
